[package]
name = "dims"
version = "0.1.0"
authors = ["william"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dims_core = {path = "../dims_core"}
dims_derive = {path = "../dims_derive"}

[features]
default = ["f32", "imp", "si"]
f32 = []
f64 = []
imp = []
si = []